### ISSUE TITLE
[Feature] Issue Hierarchy and Progress Tracking System

### ISSUE THREAD

**Issue by jezweb** [jezweb/flow-state-dev#52]
## Overview
Implement a structured issue hierarchy system with automated progress tracking to enable effective project management through GitHub Issues.

## Parent Issue
Part of #51 - GitHub Issues as Complete Project Management System

### Issue Hierarchy
1. **Epic Issues**
   - Container for related features/tasks
   - Progress tracked via checklist
   - Links to milestone
   - Shows overall completion percentage
   
2. **Feature Issues**
   - References parent epic
   - Contains implementation tasks
   - Has clear acceptance criteria
   - Medium scope (1-2 weeks)
   
3. **Task Issues**
   - Atomic, specific work items
   - Completable in 1-2 days
   - Clear definition of done
   - Links to parent feature

4. **Bug Issues**
   - Follows standard template
   - Links to affected feature
   - Includes reproduction steps

#### Automatic Progress Calculation
- Parse checklist items in issue body
- Calculate completion percentage
- Update parent issues when children close
- Show progress badges

#### Example Epic Format
```markdown
# Epic: User Authentication System

## Overview
Implement complete authentication system with email and social logins.

## Progress Tracker
- [x] Research auth providers (#101) ✅
- [x] Design database schema (#102) ✅  
- [ ] Implement email auth (#103) 🚧
- [ ] Add social auth (#104) 📅
- [ ] Create UI components (#105) 📅
- [ ] Add tests (#106) 📅
- [ ] Update documentation (#107) 📅

**Progress**: 2/7 tasks complete (29%)
**Status**: 🚧 In Progress
**Target**: Sprint 3
```

### Implementation Tasks

1. **Create Issue Templates**
   - Epic template with progress section
   - Feature template with acceptance criteria
   - Task template with time estimate
   - Bug template with reproduction

2. **Build Progress Parser**
   - GitHub Action to parse checklists
   - Calculate percentages
   - Update issue body with progress
   - Add status badges

3. **Parent-Child Linking**
   - Automated linking system
   - Update parents on child completion
   - Show dependency trees
   - Track blockers

4. **Milestone Integration**
   - Auto-add to appropriate milestone
   - Show milestone progress
   - Sprint/release tracking
   - Burndown visualization

### GitHub Action Workflow
```yaml
name: Update Issue Progress
on:
  issues:
    types: [edited, closed]
  issue_comment:
    types: [created]

jobs:
  update-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Progress
        # Parse checklist items
      - name: Calculate Percentage  
        # Calculate completion
      - name: Update Issue
        # Update progress section
      - name: Update Parent
        # If child closed, update parent
```

### Progress Tracking Format
- Use checkbox lists in issue body
- Reference related issues with #
- Status emojis: ✅ Done, 🚧 In Progress, 📅 Planned, 🚫 Blocked
- Auto-generate progress bar: ▓▓▓▓░░░░░░ 40%

## Acceptance Criteria
- [ ] Issue templates created and tested
- [ ] Progress parser accurately calculates completion
- [ ] Parent issues auto-update when children close
- [ ] Progress visible in issue lists
- [ ] Documentation for using the system
- [ ] Integration with existing labels

## Benefits
- Clear project visibility
- Automated progress tracking
- Reduced manual updates
- Better sprint planning
- Historical progress data

## Testing
- [ ] Test with various checklist formats
- [ ] Verify parent-child updates
- [ ] Test with 50+ issue projects
- [ ] Performance benchmarks
- [ ] Edge case handling
